devices:
- device_type: cisco_ios_telnet
  fast_cli: false
  global_delay_factor: 2
  host: 127.0.0.1
  name: R1
  password: ''
  port: 5000
  secret: ''
  timeout: 30
  username: ''
- device_type: cisco_ios_telnet
  fast_cli: false
  global_delay_factor: 2
  host: 127.0.0.1
  name: R2
  password: ''
  port: 5008
  secret: ''
  timeout: 30
  username: ''
