devices:
- device_type: cisco_ios_telnet
  fast_cli: false
  global_delay_factor: 2
  host: 127.0.0.1
  last_tested: '2025-07-29T15:59:30.732580'
  management_ip: 192.168.1.10
  name: R1
  password: ''
  port: 5000
  real_hostname: Baraton
  secret: ''
  timeout: 30
  username: ''
- device_type: cisco_ios_telnet
  fast_cli: false
  global_delay_factor: 2
  host: 127.0.0.1
  last_tested: '2025-07-29T15:59:38.437850'
  management_ip: null
  name: R2
  password: ''
  port: 5008
  real_hostname: R2
  secret: ''
  timeout: 30
  username: ''
